CREATE TABLE APPOINTMENT(
  APPOINTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  APPOINTMENT_DATE date NOT NULL,
  APPOINTMENT_DESCR varchar(255) NOT NULL,
  APPOINTMENT_PATID int,
  APPOINTMENT_CITY varchar(50) NOT NULL,
  APPOINTMENT_STREET varchar(50) NOT NULL,
  APPOINTMENT_STREET_NUMBER int NOT NULL,
  APPOINTMENT_ADDITION varchar(50)
);


CREATE INDEX IDX_APPOINTMENT_DATE ON APPOINTMENT(APPOINTMENT_DATE);
